help_my_plants/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('services/', include('services.urls')),
    path('checkout/', include('checkout.urls')),
    path('articles/', include('articles.urls')),
    path('profile/', include('profiles.urls')),
    path('bookings/', include('bookings.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
""" Url for the Home page """
from django.urls import path
from .import views


urlpatterns = [
    path('', views.index, name='home'),
]

services/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.all_services, name='services'),
    path('<int:service_id>/', views.service_detail, name='service_detail'),
    path('add/', views.add_service, name='add_service'),
    path('edit/<int:service_id>', views.edit_service, name='edit_service'),
    path('delete/<int:service_id>', views.delete_service, name='delete_service'),
]

checkout/models.py
""" Models for Order and related Line Items """
import uuid
from django.db.models import Sum
from django.db import models
from django.conf import settings
from services.models import Service
from profiles.models import UserProfile


class Order(models.Model):
    """Order model """
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    customer_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    date = models.DateField(auto_now_add=True)
    original_cart = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False,
                                  blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total for every item added
        """
        self.order_total = self.lineitems.aggregate(
            Sum('item_total'))['item_total__sum'] or 0

        self.total = self.order_total
        self.save()

    def save(self, *args, **kwargs):
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderItem(models.Model):
    """ Related Line Item Model """
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    service = models.ForeignKey(Service, null=False, blank=False,
                                on_delete=models.CASCADE)
    date_picked = models.DateField(auto_now_add=False, null=True, blank=True)
    item_total = models.DecimalField(max_digits=6, decimal_places=2,
                                     null=False, blank=False,
                                     editable=False, default=0)

    def save(self, *args, **kwargs):
        self.item_total = self.service.price
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Order total {self.service.price} \
                 for order number {self.order.order_number}'

services/models.py
""" Model for the Services """
from django.db import models


class Service(models.Model):
    """ Model details """
    name = models.CharField(max_length=254)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

services/forms.py
""" Service Form allowing services to be updated """
from django import forms
from .models import Service


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'text-content'

services/views.py
"""imports and viewss for Services models and views """
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Service
from .forms import ServiceForm

# Create your views here.


@login_required
def all_services(request):
    """ A view to show all services """
    services = Service.objects.all()
    context = {
        'services': services,
    }
    return render(request, 'services/services.html', context)


@login_required
def service_detail(request, service_id):
    """ a view to display individual service details """
    service = get_object_or_404(Service, pk=service_id)

    context = {
        'service': service,
    }
    return render(request, 'services/service_detail.html', context)


@login_required
def add_service(request):
    """ Add a service to the site """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only site owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ServiceForm(request.POST, request.FILES)
        if form.is_valid():
            service = form.save()
            messages.success(request, 'Successfully added service!')
            return redirect(reverse('service_detail', args=[service.id]))
        else:
            messages.error(request, 'Failed to add service. \
                Please ensure the form is valid.')
    else:
        form = ServiceForm()

    template = 'services/add_service.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_service(request, service_id):
    """ Edit a service in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only site owners can do that.')
        return redirect(reverse('home'))

    service = get_object_or_404(Service, pk=service_id)
    if request.method == 'POST':
        form = ServiceForm(request.POST, request.FILES, instance=service)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated service!')
            return redirect(reverse('service_detail', args=[service.id]))
        else:
            messages.error(request, 'Failed to update service. \
                Please ensure the form is valid.')
    else:
        form = ServiceForm(instance=service)
        messages.info(request, f'You are editing {service.name}')

    template = 'services/edit_service.html'
    context = {
        'form': form,
        'service': service,
    }

    return render(request, template, context)


@login_required
def delete_service(request, service_id):
    """ Delete a service from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only site owners can do that.')
        return redirect(reverse('home'))

    service = get_object_or_404(Service, pk=service_id)
    service.delete()
    messages.success(request, 'Service deleted!')
    return redirect(reverse('services'))

services/templates/services/add_service.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid content-container">
    <div class="row">
      <div class="col-12 text-center mt-4">
         
          <h2 class="text-heading mb-4">Service Admin</h2>

          <h3 class="text-heading2">Click here to see
            <a href="{% url 'bookings_list' %}" class="home-pg-links mr-2">All Customer Orders</a>
            Or see below to add a service:      
        </h3>    
        <hr>
        <h4 class="text-heading2">Add a Service</h4>
        <h3 class="text-heading2">Please Update details Below</h3> 
        <p class="text-content">Please note only fields with a * are required</p>        
      </div>
    </div>
<!-- Render form to update service details -->
  <div class="row">
      <div class="col-12 col-md-6 offset-md-3">
          <form method="POST" action="{% url 'add_service' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form |crispy }}
                <div class="text-right m-4">
                    <a href="{% url 'services' %}" class="btn mr-2">Cancel</a>
                    <button class="btn" type="submit">Add a Service</button>
                </div>
        </form>
      </div>
  </div>
  
</div>
{% endblock %}

services/templates/services/edit_service.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid content-container">
    <div class="row">
      <div class="col-12 text-center mt-3">
          
          <h2 class="text-heading mb-4">Service Admin</h2>
          <h5 class="text-heading2">Edit a Service</h5>
          <p class="text-content">Please note only fields with a * are required</p>
          
      </div>
    </div>

  <div class="row">
      <div class="col-12 col-md-6 offset-md-3">
          <form method="POST" action="{% url 'edit_service' service.id %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form |crispy }}
                <div class="text-right m-4">
                    <a href="{% url 'services' %}" class="btn mr-2">Cancel</a>
                    <button class="btn" type="submit">Update Service</button>
                </div>
        </form>
      </div>
  </div>
  
</div>
{% endblock %}

services/templates/services/service_detail.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container-fluid header-container">
  <div class="row">
    <div class="col"></div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid content-container">
  <div class="row">
    <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
      <div class="image-container my-5">
        {% if service.image %}
        <a href="{% url 'service_detail' service.id %}">
          <img src="{{ service.image.url }}" class="card-img-top" alt="{{ service.name }}">
        </a>
        {% else %}
        <a href="{% url 'service_detail' service.id %}">
          <img src="{{ MEDIA_URL }}no-image.png" class="card-img-top" alt="{{ service.name }}">
        </a>
        {% endif %}
      </div>
    </div>
    <div class="col-12 col-md-6 col-lg-4">
      <div class="mb-5 mt-md-5">
        <h5 class="card-title">{{ service.name}}</h5>
        <p class="text-content">{{ service.description }}</p>
        <p class="text-content"><strong>€ </strong>{{ service.price }}</p>
        {% if request.user.is_superuser %}
        <p class="ml-3">
          <a href="{% url 'edit_service' service.id %}" class="home-pg-links">Edit</a> |
          <a class="text-danger" href="{% url 'delete_service' service.id %}">Delete</a>
        </p>
        {% endif %}

        <!-- Hidden Fields as due to time constraints, have not written code 
          to pass this to order line items, then add to cart and render correctly
          Message is displayed to user and email noting business will be in touch
           and once date confirmed will be added to their profile-->
        <form action="#" method="post" id="date_picked">

          <input class="form-control Date" type="hidden" name="date_picked" data-item_id="{{ order.date_picked }}"
            id="id_date_picked">
        </form>
      </div>

      <form method="POST" class="form" action="{% url 'add_to_cart' service.id %}">
        {% csrf_token %}
        <div class="form-row">
          <div class="col-12">
            <a href="{% url 'services' %}" class="btn mt-5">
              <span class="icon">
                <i class="fas fa-chevron-circle-left"></i>
              </span>
              <span class="text-uppercase">Back to All Services</span>
            </a>
            <input type="submit" class="btn mt-5" value="Add to Cart">
          </div>
          <input type="hidden" name="redirect_url" value="{{ request.path }}">
        </div>
      </form>
    </div>
  </div>
  <div class="btt-button shadow-sm rounded-0">
    <a class="btt-link d-flex h-100">
      <i class="fas fa-angle-double-up mx-auto my-auto"></i>
    </a>
  </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}

<script>
  $('.btt-link').click(function (e) {
    window.scrollTo(0, 0)
  })
</script>
{% endblock %}

services/templates/services/services.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="container-fluid header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container-fluid content-container">
    <div class="row">
        <div class="col text-center mt3">
            <h3 class="text-heading pt-4">Services</h3>
            <hr class="w-50 mb-1">
        </div>
    </div>

    <div class="row">
        <div class="services-container col-10 offset-1">
            <div class="row mt-1 mb-2"></div>
            <div class="row">
                {% for service in services %}
                <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3">
                    <div class="card-deck">
                        <div class="card">

                            {% if service.image %}
                            <a href="{% url 'service_detail' service.id %}">
                                <img src="{{ service.image.url }}" class="card-img-top" alt="{{ service.name }}">
                            </a>
                            {% else %}

                            <a href="{% url 'service_detail' service.id %}">
                                <img src="{{ MEDIA_URL }}no-image.png" class="card-img-top" alt="{{ service.name }}">
                            </a>

                            {% endif %}


                            <div class="card-body">
                                <h5 class="card-title">{{ service.name}}</h5>
                            </div>
                            <div class="card-footer">
                                <small class="text-content">€ {{ service.price }}</small>
                                {% if request.user.is_superuser %}
                                <small>
                                    <a href="{% url 'edit_service' service.id %}" class="home-pg-links">Edit</a> |
                                    <a class="text-danger" href="{% url 'delete_service' service.id %}">Delete</a>
                                </small>
                                {% endif %}
                            </div>

                        </div>
                    </div>
                    <!-- end of card desk -->
                </div>
                <!-- code for the forloop below from Boutique Ado CI lessons -->
                {% if forloop.counter|divisibleby:1 %}
                <div class="col-12 d-sm-none mb-5">
                    <hr>
                </div>
                {% endif %}
                {% if forloop.counter|divisibleby:2 %}
                <div class="col-12 d-none d-sm-block d-md-block d-lg-none mb-5">
                    <hr>
                </div>
                {% endif %}
                {% if forloop.counter|divisibleby:3 %}
                <div class="col-12 d-none d-lg-block d-xl-none mb-5">
                    <hr>
                </div>
                {% endif %}
                {% if forloop.counter|divisibleby:4 %}
                <div class="col-12 d-none d-xl-block mb-5">
                    <hr>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="btt-button shadow-sm rounded-0">
        <a class="btt-link d-flex h-100">
            <i class="fas fa-angle-double-up text-black mx-auto my-auto"></i>
        </a>
    </div>
</div>

{% endblock %}

{% block postloadjs %}
{{ block.super }}

<script>
    $('.btt-link').click(function (e) {
        window.scrollTo(0, 0)
    })
</script>
{% endblock %}